#!/usr/bin/env python3
"""SoccerMod Arena: the small map-name switches in the plugin source tree.

Run ON the build host, inside the tree (e.g. /root/football-build). It edits the files in
place - one exact line each, nothing else is touched - after copying every file it changes to
a backup folder. Every edit must match exactly once, otherwise nothing is written at all.
Running it twice is harmless (an already applied edit is recognised and skipped).

    python3 apply_arena_switches.py <tree> [--check]

The numbers themselves live in SoccerModMvpPlugin.ArenaLayout.cs (generated by
tools/arena/generate-arena-plugin.mjs); copy that file into the plugin folder first.
"""
import pathlib
import shutil
import sys
import time

tree = pathlib.Path(sys.argv[1]) / "src/server-plugin/SoccerModMvp"
check_only = "--check" in sys.argv

EDITS = {
    "SoccerModMvpPlugin.cs": [
        # the arena counts as a foundation map: same pitch, goals and walls as v8
        ("        || string.Equals(map, OwnStadiumMapName, StringComparison.OrdinalIgnoreCase);",
         "        || string.Equals(map, OwnStadiumMapName, StringComparison.OrdinalIgnoreCase)\n        || IsArenaMap(map);"),
        ("            manifest.AddResource(ownStadium ? OwnStadiumRadarTextureResource : StadiumRadarTextureResource);",
         "            manifest.AddResource(ArenaLoading ? ArenaRadarTextureResource : ownStadium ? OwnStadiumRadarTextureResource : StadiumRadarTextureResource);"),
        ("            manifest.AddResource(ownStadium ? OwnStadiumLoadingScreenResource : StadiumLoadingScreenResource);",
         "            if (!ArenaLoading) manifest.AddResource(ownStadium ? OwnStadiumLoadingScreenResource : StadiumLoadingScreenResource);"),
    ],
    "SoccerModMvpPlugin.Atmosphere.cs": [
        ("    private bool AtmoOn => FlagFileOn(AtmoFlagFile) && string.Equals(_currentMapName, FoundationMapName, StringComparison.OrdinalIgnoreCase) && AtmoSet.Director;",
         "    private bool AtmoOn => FlagFileOn(AtmoFlagFile) && (string.Equals(_currentMapName, FoundationMapName, StringComparison.OrdinalIgnoreCase) || OnArena) && AtmoSet.Director;"),
    ],
    "SoccerModMvpPlugin.AtmoCrowd.cs": [
        ('    private const string AtmoCrowdDir = "models/soccermod/atmo/crowd/";',
         '    private const string AtmoCrowdDirV8 = "models/soccermod/atmo/crowd/";\n    private static string AtmoCrowdDir => ArenaLoading ? ArenaCrowdDir : AtmoCrowdDirV8;   // ArenaLayout.cs'),
    ],
    "SoccerModMvpPlugin.AtmoRing.cs": [
        ('    private const string AtmoRingModel = "models/soccermod/atmo/light_ring.vmdl";',
         '    private const string AtmoRingModelV8 = "models/soccermod/atmo/light_ring.vmdl";\n    private static string AtmoRingModel => ArenaLoading ? ArenaRingModel : AtmoRingModelV8;   // ArenaLayout.cs'),
        ("    private static IEnumerable<(Vector At, float Yaw, float Scale)> AtmoRingSpots()\n    {",
         "    private static IEnumerable<(Vector At, float Yaw, float Scale)> AtmoRingSpots() => ArenaLoading ? ArenaRingSpots() : AtmoRingSpotsV8();\n    private static IEnumerable<(Vector At, float Yaw, float Scale)> AtmoRingSpotsV8()\n    {"),
    ],
    "SoccerModMvpPlugin.AtmoBanners.cs": [
        ('            kv.SetVector("origin", new Vector(x, side * 1956f, 880.5f));\n            kv.SetAngle("angles", new QAngle(0, side > 0 ? 0 : 180, 0));',
         '            var (bannerAt, bannerYaw) = AtmoBannerSpot(x, side);   // ArenaLayout.cs (v8: x, side * 1956, 880.5)\n            kv.SetVector("origin", bannerAt);\n            kv.SetAngle("angles", new QAngle(0, bannerYaw, 0));'),
    ],
    "SoccerModMvpPlugin.AtmoSpider.cs": [
        ("    private static readonly Vector[] AtmoSpiderAnchors =",
         "    private Vector[] AtmoSpiderAnchors => OnArena ? ArenaSpiderAnchors : AtmoSpiderAnchorsV8;   // ArenaLayout.cs\n    private static readonly Vector[] AtmoSpiderAnchorsV8 ="),
    ],
    "SoccerModMvpPlugin.AtmoFx.cs": [
        ("    private static readonly (float X, float Y)[] AtmoStandCentres = { (1950f, 0f), (-1950f, 0f), (0f, 2350f), (0f, -2350f) };",
         "    private static readonly (float X, float Y)[] AtmoStandCentresV8 = { (1950f, 0f), (-1950f, 0f), (0f, 2350f), (0f, -2350f) };\n    private (float X, float Y)[] AtmoStandCentres => OnArena ? ArenaStandCentres : AtmoStandCentresV8;   // ArenaLayout.cs"),
        ('            AtmoParticle($"flare_{colour}", new Vector(x, fanSign * 2074f, 122f), 11.0);',
         '            AtmoParticle($"flare_{colour}", AtmoEndRowSpot(x, fanSign), 11.0);'),
        ('            AtmoParticle($"confetti_cannon_{colour}", new Vector(1300f, fanSign * 1962f, 185f), 10.0);',
         '            AtmoParticle($"confetti_cannon_{colour}", AtmoCannonSpot(1f, fanSign), 10.0);'),
        ('            AtmoParticle($"confetti_cannon_{colour}", new Vector(-1300f, fanSign * 1962f, 185f), 10.0);',
         '            AtmoParticle($"confetti_cannon_{colour}", AtmoCannonSpot(-1f, fanSign), 10.0);'),
    ],
    "SoccerModMvpPlugin.AtmoGoalFx.cs": [
        ('                    AtmoParticle("flare_gold", new Vector(sideX, y, 122f), 11.0);',
         '                    AtmoParticle("flare_gold", AtmoSideRowSpot(sideX, y), 11.0);'),
    ],
    "SoccerModMvpPlugin.AtmoShow.cs": [
        ('                    AtmoParticle($"flare_{colour}", new Vector(x, fan * 2074f, 122f), 9.0);',
         '                    AtmoParticle($"flare_{colour}", AtmoEndRowSpot(x, fan), 9.0);'),
    ],
    "SoccerModMvpPlugin.MapScoreText.cs": [
        ("    private const float MapScoreTextScreenY = 1943.5f;",
         "    private float MapScoreTextScreenY => OnArena ? ArenaScoreScreenY : 1943.5f;   // ArenaLayout.cs\n    private float MapScoreScale => OnArena ? ArenaScoreScale : 1.0f;"),
        ("    private const float MapScoreTextCenterZ = 888.0f;",
         "    private float MapScoreTextCenterZ => OnArena ? ArenaScoreCenterZ : 888.0f;"),
        ("        text.WorldUnitsPerPx = _mapScoreTextUnitsPerPx;",
         "        text.WorldUnitsPerPx = _mapScoreTextUnitsPerPx * MapScoreScale;"),
    ],
    "SoccerModMvpPlugin.MapScoreGoalFx.cs": [
        ("        _goalFxUnitsPerPx = Math.Min(_mapScoreTextUnitsPerPx, GoalFxMaxWidth / estimatedPx);",
         "        _goalFxUnitsPerPx = Math.Min(_mapScoreTextUnitsPerPx, GoalFxMaxWidth / estimatedPx) * MapScoreScale;"),
    ],
    "SoccerModMvpPlugin.MapProfile.cs": [
        # the arena's goals stand 7 units further out (CS:S positions): GoalShiftY in ArenaLayout.cs
        ("    private float GoalLineNow => ActiveFrame?.GoalLineY ?? _goalLineY;",
         "    private float GoalLineNow => ActiveFrame?.GoalLineY ?? _goalLineY + GoalShiftY;"),
        ('        IsFoundationMap(_currentMapName) ? new NetGoals(0.0f, 0.0f, GoalFrameLineY, StadiumPitchPlaneZ, "v8")',
         '        IsFoundationMap(_currentMapName) ? new NetGoals(0.0f, 0.0f, GoalFrameLineY + GoalShiftY, StadiumPitchPlaneZ, "v8")'),
    ],
    "SoccerModMvpPlugin.Match.cs": [
        ("    private float GoalPlaneY => MathF.Min(_goalLineY + _goalDepthRequired * _ballSize, NetBackstopY - BallCollisionRadius - 5.0f);",
         "    private float GoalPlaneY => MathF.Min(_goalLineY + _goalDepthRequired * _ballSize, NetBackstopY - BallCollisionRadius - 5.0f) + GoalShiftY;"),
    ],
    "SoccerModMvpPlugin.GoalFrameSound.cs": [
        ("            GoalHalfWidthNow, ActiveFrame is not null ? GoalLineNow : GoalFrameLineY, StadiumPitchPlaneZ + GoalApertureMaxNow);",
         "            GoalHalfWidthNow, ActiveFrame is not null ? GoalLineNow : GoalFrameLineY + GoalShiftY, StadiumPitchPlaneZ + GoalApertureMaxNow);"),
        ("        return MathF.Abs(MathF.Abs(local.Y) - (ActiveFrame is not null ? GoalLineNow : GoalFrameLineY)) <= 120f",
         "        return MathF.Abs(MathF.Abs(local.Y) - (ActiveFrame is not null ? GoalLineNow : GoalFrameLineY + GoalShiftY)) <= 120f"),
    ],
    "SoccerModMvpPlugin.DynamicNet.cs": [
        # the map's net brushes are found by position: 7 units further out on the arena
        ("                ? brush.AbsOrigin is { } o && MathF.Abs(o.X) <= 1f && MathF.Abs(MathF.Abs(o.Y) - DynamicNetBrushY) <= 1f && MathF.Abs(o.Z - DynamicNetBrushZ) <= 1f",
         "                ? brush.AbsOrigin is { } o && MathF.Abs(o.X) <= 1f && MathF.Abs(MathF.Abs(o.Y) - DynamicNetBrushY - GoalShiftY) <= 1f && MathF.Abs(o.Z - DynamicNetBrushZ) <= 1f"),
    ],
    "SoccerModMvpPlugin.Grass.cs": [
        # the bake set carries v8's roof shadow; the arena pitch has none, so it gets the lit tiles
        ("        _grassBakeWanted = !File.Exists(ConfigPath(GrassFineFlagFile));\n        RegisterListener<Listeners.OnServerPrecacheResources>(manifest =>",
         "        _grassBakeWanted = !File.Exists(ConfigPath(GrassFineFlagFile)) && !ArenaLoading;\n        RegisterListener<Listeners.OnServerPrecacheResources>(manifest =>"),
        ("            _grassBakeWanted = !File.Exists(ConfigPath(GrassFineFlagFile));\n            _grassBakePrecached = false;",
         "            _grassBakeWanted = !File.Exists(ConfigPath(GrassFineFlagFile)) && !ArenaLoading;   // arena: no roof shadow on the pitch (ArenaLayout.cs)\n            _grassBakePrecached = false;"),
    ],
    "SoccerModMvpPlugin.PitchDesign.cs": [
        ('            if (!MountedAddonFiles().Contains(PitchDesignModel + "_c"))',
         '            if (ArenaLoading)\n            {\n                // the arena has its own high-resolution design floors in the map\'s Workshop item (ArenaLayout.cs)\n                if (!MountedAddonFiles().Contains(ArenaPitchDesignModels[0] + "_c"))\n                {\n                    Logger.LogInformation("[SM2DIAG] pitch_design_unavailable reason=model_not_in_mounted_workshop_items model={Model}", ArenaPitchDesignModels[0]);\n                    return;\n                }\n                foreach (var model in ArenaPitchDesignModels) manifest.AddResource(model);\n                _pitchDesignPrecached = true;\n                return;\n            }\n            if (!MountedAddonFiles().Contains(PitchDesignModel + "_c"))'),
        ("    private int PitchDesignSkin(int i) => i + 4 * GrassDesignMode;",
         "    private int PitchDesignSkin(int i) => OnArena ? 0 : i + 4 * GrassDesignMode;   // arena: one model per design"),
        ('            keyValues.SetString("model", PitchDesignModel);',
         '            keyValues.SetString("model", OnArena ? ArenaPitchDesignModels[skin] : PitchDesignModel);'),
    ],
}

plan, problems = [], []
for name, edits in EDITS.items():
    path = tree / name
    if not path.exists():
        problems.append(f"{name}: file missing")
        continue
    text = path.read_text(encoding="utf-8")
    new = text
    for old, repl in edits:
        if repl in new:
            continue                      # already applied
        n = new.count(old)
        if n != 1:
            problems.append(f"{name}: expected 1 match, found {n}: {old.strip()[:80]}")
            continue
        new = new.replace(old, repl)
    if new != text:
        plan.append((path, new))

if not (tree / "SoccerModMvpPlugin.ArenaLayout.cs").exists():
    problems.append("SoccerModMvpPlugin.ArenaLayout.cs is not in the plugin folder yet")
if problems:
    print("NOT applied:")
    for p in problems:
        print("  " + p)
    sys.exit(1)
if check_only:
    print(f"check ok: {len(plan)} file(s) would change")
    sys.exit(0)
backup = pathlib.Path(f"/root/arena-plugin/backup-{time.strftime('%Y%m%d-%H%M%S')}")
backup.mkdir(parents=True, exist_ok=True)
for path, new in plan:
    shutil.copy2(path, backup / path.name)
    path.write_text(new, encoding="utf-8")
    print(f"edited {path.name}")
print(f"{len(plan)} file(s) changed, originals in {backup}" if plan else "nothing to do (already applied)")
