using CounterStrikeSharp.API;
using CounterStrikeSharp.API.Modules.Utils;

namespace SoccerModMvp;

// GENERATED by tools/arena/generate-arena-plugin.mjs from tools/arena/layout.mjs - do not edit by hand.
//
// ka_soccermod_stadium, first called soccer_soccermod_arena (2026-10-01, owner: "an own version of the v8 stadium, round, realistic,
// as a separate map" and "make sure our mod and all its visual changes work on the new map").
// The pitch is v8's to the unit (grass, lines, goals, nets, low boards, invisible walls, dugouts),
// so everything that happens on the pitch runs as on v8. The stands, roof and screens are new:
// the stadium effects take their spots from here on that map. v8 keeps its own numbers.
public sealed partial class SoccerModMvpPlugin
{
    // 2026-10-01 owner: the map is called ka_soccermod_stadium. Its first Workshop revisions were
    // soccer_soccermod_arena; both names count, so a server still on an old revision keeps working.
    private const string ArenaMapName = "ka_soccermod_stadium";
    private const string ArenaFirstMapName = "soccer_soccermod_arena";
    private static bool IsArenaMap(string? map) => string.Equals(map, ArenaMapName, StringComparison.OrdinalIgnoreCase)
        || string.Equals(map, ArenaFirstMapName, StringComparison.OrdinalIgnoreCase);
    // during the map (the hot paths); while a map loads _currentMapName is still the old one: use ArenaLoading there
    private bool OnArena => IsArenaMap(_currentMapName);
    private static bool ArenaLoading => IsArenaMap(Server.MapName);

    // Owner 2026-10-01: the arena's goals stand where CS:S (ka_soccer_xsl_stadium_b1) has them, 7 units
    // further out than v8's (post front |y| 1384 instead of 1377; width and height are the same).
    // Everything measured from a goal - detection plane, goal frame, moving net, net pocket, post
    // sounds, keeper box - moves with it. The painted lines did not move.
    private const float ArenaGoalShift = 7f;
    private float GoalShiftY => OnArena ? ArenaGoalShift : 0f;

    private static string ArenaRadarTextureResource => "panorama/images/overheadmaps/"
        + (string.Equals(Server.MapName, ArenaFirstMapName, StringComparison.OrdinalIgnoreCase) ? ArenaFirstMapName : ArenaMapName) + "_radar_psd.vtex";
    private const string ArenaCrowdDir = "models/soccermod/atmo/crowd_arena/";
    private const string ArenaRingModel = "models/soccermod_arena/light_ring.vmdl";
    // the four pitch designs as geometry with tiling 12-texel-per-unit grass (index = design - 1)
    private static readonly string[] ArenaPitchDesignModels =
    {
        "models/soccermod_arena/pitch_design_stripes.vmdl", "models/soccermod_arena/pitch_design_lengthwise.vmdl",
        "models/soccermod_arena/pitch_design_diamond.vmdl", "models/soccermod_arena/pitch_design_circles.vmdl",
    };

    // LED ring: 104 segments of 160 x 40 on the upper stand's fascia (z 443-487),
    // counter-clockwise from the middle of the east side, facing the pitch.
    private static readonly (float X, float Y, float Yaw, float Scale)[] ArenaRingSpotTable =
    {
        (2162.5f, 79.8f, -180f, 0.98f),
        (2162.45f, 239.4f, -179.97f, 0.98f),
        (2162.19f, 399f, -179.84f, 0.98f),
        (2161.33f, 558.6f, -179.54f, 0.98f),
        (2159.23f, 718.18f, -178.95f, 0.98f),
        (2154.85f, 877.71f, -177.91f, 0.98f),
        (2146.88f, 1037.09f, -176.36f, 0.98f),
        (2133.66f, 1196.1f, -174.14f, 0.98f),
        (2113.43f, 1354.34f, -171.29f, 0.98f),
        (2083.93f, 1511.07f, -167.39f, 0.98f),
        (2042.88f, 1665.11f, -162.76f, 0.98f),
        (1988.32f, 1814.81f, -157.19f, 0.98f),
        (1918.35f, 1957.87f, -150.68f, 0.98f),
        (1831.97f, 2091.57f, -143.59f, 0.98f),
        (1729.05f, 2212.91f, -135.8f, 0.98f),
        (1611.01f, 2319.6f, -128.42f, 0.98f),
        (1479.96f, 2409.79f, -120.65f, 0.98f),
        (1338.13f, 2482.03f, -113.33f, 0.98f),
        (1188.6f, 2536.83f, -106.92f, 0.98f),
        (1034.1f, 2575.8f, -101.4f, 0.98f),
        (876.72f, 2601.37f, -97.06f, 0.98f),
        (717.93f, 2616.45f, -93.78f, 0.98f),
        (558.55f, 2624.12f, -91.73f, 0.98f),
        (398.99f, 2627.33f, -90.58f, 0.98f),
        (239.4f, 2628.31f, -90.12f, 0.98f),
        (79.8f, 2628.48f, -90.01f, 0.98f),
        (-79.8f, 2628.48f, -89.99f, 0.98f),
        (-239.4f, 2628.31f, -89.88f, 0.98f),
        (-398.99f, 2627.33f, -89.42f, 0.98f),
        (-558.55f, 2624.12f, -88.27f, 0.98f),
        (-717.93f, 2616.45f, -86.22f, 0.98f),
        (-876.72f, 2601.37f, -82.94f, 0.98f),
        (-1034.1f, 2575.8f, -78.6f, 0.98f),
        (-1188.6f, 2536.83f, -73.08f, 0.98f),
        (-1338.13f, 2482.03f, -66.67f, 0.98f),
        (-1479.96f, 2409.79f, -59.35f, 0.98f),
        (-1611.01f, 2319.6f, -51.58f, 0.98f),
        (-1729.05f, 2212.91f, -44.2f, 0.98f),
        (-1831.97f, 2091.57f, -36.41f, 0.98f),
        (-1918.35f, 1957.87f, -29.32f, 0.98f),
        (-1988.32f, 1814.81f, -22.81f, 0.98f),
        (-2042.88f, 1665.11f, -17.24f, 0.98f),
        (-2083.93f, 1511.07f, -12.61f, 0.98f),
        (-2113.43f, 1354.34f, -8.71f, 0.98f),
        (-2133.66f, 1196.1f, -5.86f, 0.98f),
        (-2146.88f, 1037.09f, -3.64f, 0.98f),
        (-2154.85f, 877.71f, -2.09f, 0.98f),
        (-2159.23f, 718.18f, -1.05f, 0.98f),
        (-2161.33f, 558.6f, -0.46f, 0.98f),
        (-2162.19f, 399f, -0.16f, 0.98f),
        (-2162.45f, 239.4f, -0.03f, 0.98f),
        (-2162.5f, 79.8f, 0f, 0.98f),
        (-2162.5f, -79.8f, 0f, 0.98f),
        (-2162.45f, -239.4f, 0.03f, 0.98f),
        (-2162.19f, -399f, 0.16f, 0.98f),
        (-2161.33f, -558.6f, 0.46f, 0.98f),
        (-2159.23f, -718.18f, 1.05f, 0.98f),
        (-2154.85f, -877.71f, 2.09f, 0.98f),
        (-2146.88f, -1037.09f, 3.64f, 0.98f),
        (-2133.66f, -1196.1f, 5.86f, 0.98f),
        (-2113.43f, -1354.34f, 8.71f, 0.98f),
        (-2083.93f, -1511.07f, 12.61f, 0.98f),
        (-2042.88f, -1665.11f, 17.24f, 0.98f),
        (-1988.32f, -1814.81f, 22.81f, 0.98f),
        (-1918.35f, -1957.87f, 29.32f, 0.98f),
        (-1831.97f, -2091.57f, 36.41f, 0.98f),
        (-1729.05f, -2212.91f, 44.2f, 0.98f),
        (-1611.01f, -2319.6f, 51.58f, 0.98f),
        (-1479.96f, -2409.79f, 59.35f, 0.98f),
        (-1338.13f, -2482.03f, 66.67f, 0.98f),
        (-1188.6f, -2536.83f, 73.08f, 0.98f),
        (-1034.1f, -2575.8f, 78.6f, 0.98f),
        (-876.72f, -2601.37f, 82.94f, 0.98f),
        (-717.93f, -2616.45f, 86.22f, 0.98f),
        (-558.55f, -2624.12f, 88.27f, 0.98f),
        (-398.99f, -2627.33f, 89.42f, 0.98f),
        (-239.4f, -2628.31f, 89.88f, 0.98f),
        (-79.8f, -2628.48f, 89.99f, 0.98f),
        (79.8f, -2628.48f, 90.01f, 0.98f),
        (239.4f, -2628.31f, 90.12f, 0.98f),
        (398.99f, -2627.33f, 90.58f, 0.98f),
        (558.55f, -2624.12f, 91.73f, 0.98f),
        (717.93f, -2616.45f, 93.78f, 0.98f),
        (876.72f, -2601.37f, 97.06f, 0.98f),
        (1034.1f, -2575.8f, 101.4f, 0.98f),
        (1188.6f, -2536.83f, 106.92f, 0.98f),
        (1338.13f, -2482.03f, 113.33f, 0.98f),
        (1479.96f, -2409.79f, 120.65f, 0.98f),
        (1611.01f, -2319.6f, 128.42f, 0.98f),
        (1729.05f, -2212.91f, 135.8f, 0.98f),
        (1831.97f, -2091.57f, 143.59f, 0.98f),
        (1918.35f, -1957.87f, 150.68f, 0.98f),
        (1988.32f, -1814.81f, 157.19f, 0.98f),
        (2042.88f, -1665.11f, 162.76f, 0.98f),
        (2083.93f, -1511.07f, 167.39f, 0.98f),
        (2113.43f, -1354.34f, 171.29f, 0.98f),
        (2133.66f, -1196.1f, 174.14f, 0.98f),
        (2146.88f, -1037.09f, 176.36f, 0.98f),
        (2154.85f, -877.71f, 177.91f, 0.98f),
        (2159.23f, -718.18f, 178.95f, 0.98f),
        (2161.33f, -558.6f, 179.54f, 0.98f),
        (2162.19f, -399f, 179.84f, 0.98f),
        (2162.45f, -239.4f, 179.97f, 0.98f),
        (2162.5f, -79.8f, 180f, 0.98f),
    };
    private const float ArenaRingZ = 465f;
    private static IEnumerable<(Vector At, float Yaw, float Scale)> ArenaRingSpots()
    {
        foreach (var (x, y, yaw, scale) in ArenaRingSpotTable) yield return (new Vector(x, y, ArenaRingZ), yaw, scale);
    }

    // Waving banners: under the roof edge at both ends, left and right of the video wall.
    // Same order as on v8: the +y end first, x -1100, -546, 546, 1100.
    private static readonly (float X, float Y, float Z, float Yaw)[] ArenaBannerSpots =
    {
        (-1098.35f, 2221.18f, 1227.99f, 17.14f),
        (-543.47f, 2294.44f, 1216.15f, 1.64f),
        (543.47f, 2294.44f, 1216.15f, -1.64f),
        (1098.35f, 2221.18f, 1227.99f, -17.14f),
        (-1098.35f, -2221.18f, 1227.99f, 162.86f),
        (-543.47f, -2294.44f, 1216.15f, 178.36f),
        (543.47f, -2294.44f, 1216.15f, 181.64f),
        (1098.35f, -2221.18f, 1227.99f, 197.14f),
    };

    // Spidercam cables: the roof's inner edge at the four corners.
    private static readonly Vector[] ArenaSpiderAnchors =
    {
        new(1506.43f, 1989.38f, 1291.44f),
        new(-1506.43f, 1989.38f, 1291.44f),
        new(-1506.43f, -1989.38f, 1291.44f),
        new(1506.43f, -1989.38f, 1291.44f),
    };

    // Score screens: two upright video walls (800 x 200) under the roof edge; the picture has a red
    // and a blue score box 70 units left and right of this point, 117 wide and 115 high.
    private const float ArenaScoreScreenY = 2317f;
    private const float ArenaScoreCenterZ = 1090.77f;
    private const float ArenaScoreScale = 1.35f;   // numbers and GOALLL!! this much bigger than on v8's small roof screens

    // Stands: front of the lower stand |x/1604|^4.5 + |y/2070|^4.5 = 1; the first row of seats lies
    // 82 units behind it at z 55.
    private static readonly (float X, float Y)[] ArenaStandCentres = { (2164f, 0f), (-2164f, 0f), (0f, 2630f), (0f, -2630f) };
    private static Vector ArenaRowSpot(float x, float y, bool end, float behind, float z)
    {
        const float a = 1604f, b = 2070f, e = 4.5f;
        // the point of the front curve at this x (ends) or y (sides), then out along the curve normal
        float cx, cy;
        if (end) { cx = Math.Clamp(x, -a * 0.98f, a * 0.98f); cy = MathF.Sign(y) * b * MathF.Pow(1f - MathF.Pow(MathF.Abs(cx) / a, e), 1f / e); }
        else { cy = Math.Clamp(y, -b * 0.98f, b * 0.98f); cx = MathF.Sign(x) * a * MathF.Pow(1f - MathF.Pow(MathF.Abs(cy) / b, e), 1f / e); }
        var nx = MathF.Sign(cx) * MathF.Pow(MathF.Abs(cx), e - 1f) / MathF.Pow(a, e);
        var ny = MathF.Sign(cy) * MathF.Pow(MathF.Abs(cy), e - 1f) / MathF.Pow(b, e);
        var len = MathF.Sqrt(nx * nx + ny * ny);
        return new Vector(cx + nx / len * behind, cy + ny / len * behind, z);
    }

    // ---- what the stadium modules ask (v8 numbers stay where they were measured) ---------------
    // flares in the fans' front row behind a goal (v8: lower tier front row y +-2074, z 107)
    private Vector AtmoEndRowSpot(float x, int fanSign) => OnArena ? ArenaRowSpot(x, fanSign, true, 82f, 70f) : new Vector(x, fanSign * 2074f, 122f);
    // flares along a side stand's front row (v8: |x| 1716)
    private Vector AtmoSideRowSpot(float sideX, float y) => OnArena ? ArenaRowSpot(sideX, y, false, 82f, 70f) : new Vector(sideX, y, 122f);
    // confetti cannons at the foot of the fans' end
    private Vector AtmoCannonSpot(float sideSign, int fanSign) => OnArena ? ArenaRowSpot(sideSign * 1150f, fanSign, true, 5f, 56f) : new Vector(sideSign * 1300f, fanSign * 1962f, 185f);
    // waving banners (v8: on the roof fascia, y +-1956, z 880.5); x is one of AtmoBannerXs
    private (Vector At, float Yaw) AtmoBannerSpot(float x, int side)
    {
        if (!OnArena) return (new Vector(x, side * 1956f, 880.5f), side > 0 ? 0f : 180f);
        var i = (side > 0 ? 0 : 4) + (x < -800f ? 0 : x < 0f ? 1 : x < 800f ? 2 : 3);
        var (bx, by, bz, yaw) = ArenaBannerSpots[i];
        return (new Vector(bx, by, bz), yaw);
    }
}
