using CounterStrikeSharp.API;
using CounterStrikeSharp.API.Core;
using CounterStrikeSharp.API.Modules.Commands;
using CounterStrikeSharp.API.Modules.Utils;
using Microsoft.Extensions.Logging;

namespace SoccerModMvp;

// 2026-09-26 owner: "3D grass" like ka_soccer_night_pro_3D, rebuilt with our
// own files (tools/grass/generate-shell-grass.mjs), on every map whose pitch
// matches soccer_cssl_stadium_v8, and switchable per player (default on).
//
// The grass is one prop_dynamic of the Feature Package model
// models/soccermod/grass_shell.vmdl: 9 translucent shell layers over
// x ±1280, y ±1664 plus white layers over the painted lines. It never
// collides (solid 0 + DisableCollision, no physics in the model), so ball,
// players and every Masks.Solid trace are unaffected.
//
// Compatibility is measured, not taken from the map name: at the first round
// of a map the floor is traced at five points and the four walls at their
// cssl_v8 positions. Only then is the grass spawned (and offered in the
// menu). It is also never spawned before the Workshop item carrying the model
// is mounted on the server, which would show the ERROR model instead.
// Players who switched it off do not receive the entity (CheckTransmit
// Remove only; TransmitEntities.Add has crashed this server).
public sealed partial class SoccerModMvpPlugin
{
    // 80 tiles (8 x 10, 320 x 332.8 units, generated by
    // tools/grass/generate-shell-grass.mjs): CS2 lights a dynamic prop with a
    // single sample, so one pitch-sized prop could not show the stadium roof
    // shadow baked into the floor. Each tile model is centred on its tile.
    private const string GrassModelPrefix = "models/soccermod/grass_shell_";
    private const int GrassTilesX = 8, GrassTilesY = 10;
    private const float GrassHalfX = 1280.0f, GrassHalfY = 1664.0f;
    private static string GrassTileModel(int tx, int ty) => $"{GrassModelPrefix}{tx}_{ty}.vmdl";
    private static readonly string GrassModel = GrassTileModel(0, 0);
    private const string GrassTargetName = "sm2_grass_shell";
    private const float GrassWallTolerance = 12.0f;
    private const float GrassFloorTolerance = 4.0f;

    private readonly List<CDynamicProp> _grassTiles = new();
    private bool GrassSpawned => _grassTiles.Count > 0 && _grassTiles.All(t => t.IsValid);
    private bool _grassChecked;
    private float? _grassFloorZ;
    private bool _grassMissingLogged;

    private void GrassOnLoad(bool hotReload)
    {
        AddCommand("css_grass", "Switch the 3D grass on or off for yourself (!grass [on|off]).", OnGrassCommand);
        AddCommand("css_sm2grass", "Admin: 3D grass server mode auto|off, default on|off, status.", OnGrassAdminCommand);
        RegisterListener<Listeners.CheckTransmit>(GrassCheckTransmit);
        RegisterListener<Listeners.OnMapStart>(_ =>
        {
            _grassTiles.Clear();
            _grassChecked = false;
            _grassFloorZ = null;
            _grassMissingLogged = false;
        });
        if (hotReload)
        {
            // A reload keeps the old entities alive; remove them and spawn afresh.
            foreach (var old in Utilities.FindAllEntitiesByDesignerName<CDynamicProp>("prop_dynamic")
                         .Where(e => e.IsValid && e.Entity?.Name == GrassTargetName).ToList())
                old.Remove();
            AddTimer(1.0f, () => GrassEnsure("hot_reload"));
        }
    }

    private void GrassOnUnload() => RemoveGrass("unload");

    private bool GrassInstalled()
    {
        var installed = MountedAddonFiles().Contains(GrassModel + "_c");
        if (installed && _menuParity.GrassFirstAvailableUnix == 0)
        {
            _menuParity.GrassFirstAvailableUnix = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
            SaveJsonAtomic(MenuParityFile, _menuParity);
        }
        if (!installed && !_grassMissingLogged)
        {
            _grassMissingLogged = true;
            Logger.LogInformation("[SM2DIAG] grass_unavailable reason=model_not_in_mounted_workshop_items model={Model}", GrassModel);
        }
        return installed;
    }

    private bool GrassAvailable => _grassFloorZ is not null && !string.Equals(_menuParity.GrassServerMode, "off", StringComparison.OrdinalIgnoreCase);

    private const long GrassGraceSeconds = 24 * 3600;
    private readonly HashSet<ulong> _grassHintShown = new();

    private bool GrassInGracePeriod =>
        _menuParity.GrassFirstAvailableUnix == 0
        || DateTimeOffset.UtcNow.ToUnixTimeSeconds() - _menuParity.GrassFirstAvailableUnix < GrassGraceSeconds;

    // A player's own choice wins; otherwise the server default, which stays
    // off during the first 24 h after the grass arrived (Workshop copies lag).
    private bool GrassOn(CCSPlayerController player) =>
        _menuParity.Grass.TryGetValue(SteamIdOf(player), out var on) ? on : _menuParity.GrassDefault && !GrassInGracePeriod;

    private void GrassHint(CCSPlayerController player)
    {
        var id = SteamIdOf(player);
        if (id == 0 || !GrassAvailable || _menuParity.Grass.ContainsKey(id) || !GrassInGracePeriod || !_grassHintShown.Add(id)) return;
        player.PrintToChat(" [SM] New: 3D grass on this pitch. Type !grass to switch it on (if you see ERROR, restart CS2 so Steam updates the SoccerMod Workshop item).");
    }

    private void SetGrass(CCSPlayerController player, bool on)
    {
        var id = SteamIdOf(player);
        if (id == 0) return;
        _menuParity.Grass[id] = on;
        SaveJsonAtomic(MenuParityFile, _menuParity);
        player.PrintToChat(on
            ? " \x04[SM]\x01 3D grass: \x04on\x01 (switch it off with !grass off)."
            : " \x04[SM]\x01 3D grass: \x07off\x01 (switch it on with !grass on).");
    }

    // Called from OnRoundStart: the round restart removes plugin-made entities.
    private void GrassOnRoundStart() => AddTimer(0.5f, () => GrassEnsure("round_start"));

    private void GrassEnsure(string reason)
    {
        if (string.Equals(_menuParity.GrassServerMode, "off", StringComparison.OrdinalIgnoreCase))
        {
            RemoveGrass("server_off");
            return;
        }
        if (GrassSpawned || !GrassInstalled()) return;
        if (!_grassChecked)
        {
            _grassChecked = true;
            _grassFloorZ = DetectCsslPitchFloor(out var detail);
            Logger.LogInformation("[SM2DIAG] grass_pitch_check map={Map} compatible={Compatible} {Detail}",
                Server.MapName, _grassFloorZ is not null, detail);
        }
        if (_grassFloorZ is not { } floorZ) return;

        RemoveGrass("respawn");
        var tileW = 2 * GrassHalfX / GrassTilesX;
        var tileH = 2 * GrassHalfY / GrassTilesY;
        for (var ty = 0; ty < GrassTilesY; ty++)
        for (var tx = 0; tx < GrassTilesX; tx++)
        {
            var tile = Utilities.CreateEntityByName<CDynamicProp>("prop_dynamic");
            if (tile is null || !tile.IsValid)
            {
                Logger.LogError("[SM2DIAG] grass_create_failed reason={Reason} tile={X},{Y}", reason, tx, ty);
                RemoveGrass("create_failed");
                return;
            }
            using var keyValues = new CEntityKeyValues();
            keyValues.SetString("targetname", GrassTargetName);
            keyValues.SetString("model", GrassTileModel(tx, ty));
            keyValues.SetInt("solid", 0);
            keyValues.SetInt("disableshadows", 1);
            keyValues.SetVector("origin", new Vector(-GrassHalfX + (tx + 0.5f) * tileW, -GrassHalfY + (ty + 0.5f) * tileH, floorZ));
            keyValues.SetAngle("angles", new QAngle(0.0f, 0.0f, 0.0f));
            tile.DispatchSpawn(keyValues);
            if (!tile.IsValid) continue;
            tile.Entity!.Name = GrassTargetName;
            tile.AcceptInput("DisableCollision");
            _grassTiles.Add(tile);
        }
        foreach (var player in Utilities.GetPlayers()) if (player.IsValid && !player.IsBot) GrassHint(player);
        Logger.LogInformation("[SM2DIAG] grass_spawned reason={Reason} tiles={Tiles} floorZ={Z:F2}", reason, _grassTiles.Count, floorZ);
    }

    private void RemoveGrass(string reason)
    {
        var removed = 0;
        foreach (var tile in _grassTiles)
        {
            if (!tile.IsValid) continue;
            tile.Remove();
            removed++;
        }
        _grassTiles.Clear();
        if (removed > 0) Logger.LogInformation("[SM2DIAG] grass_removed reason={Reason} tiles={Tiles}", reason, removed);
    }

    // The cssl_v8 pitch: flat floor (z about -32) across x ±1280, y ±1664,
    // side walls at |x| = 1280 and end walls at |y| = 1664. The side walls are
    // sampled at y = ±900 (away from the tunnel doors near the halfway line),
    // the end walls at x = ±700 (away from the goals).
    private float? DetectCsslPitchFloor(out string detail)
    {
        var options = new TraceOptions { InteractsWith = Masks.SolidBrushOnly };
        var floors = new List<float>();
        // Not the centre: the ball rests on the kick-off spot (a trace there
        // hit it at z 0.7 on 2026-09-26). The ball is ignored as well.
        foreach (var (x, y) in new[] { (500f, 700f), (1100f, 1500f), (-1100f, 1500f), (1100f, -1500f), (-1100f, -1500f) })
        {
            var trace = Trace.TraceEndShape(new Vector(x, y, StadiumPitchPlaneZ + 64.0f), new Vector(x, y, StadiumPitchPlaneZ - 200.0f), _ball, options);
            if (!trace.DidHit() || trace.Normal.Z < 0.9f)
            {
                detail = $"floor_missing_at=({x:F0},{y:F0})";
                return null;
            }
            floors.Add(trace.EndPos.Z);
        }
        var floor = floors.Average();
        if (floors.Any(z => MathF.Abs(z - floor) > 1.0f) || MathF.Abs(floor - StadiumPitchPlaneZ) > GrassFloorTolerance)
        {
            detail = $"floor_not_flat_or_wrong_height floors={string.Join('/', floors.Select(z => z.ToString("F1")))}";
            return null;
        }

        var knee = floor + 40.0f;
        var walls = new List<string>();
        bool Wall(Vector from, Vector dir, float expected, bool alongX)
        {
            var trace = Trace.TraceEndShape(from, new Vector(from.X + dir.X * 2000.0f, from.Y + dir.Y * 2000.0f, knee), null, options);
            var at = alongX ? MathF.Abs(trace.EndPos.X) : MathF.Abs(trace.EndPos.Y);
            walls.Add($"{(alongX ? "x" : "y")}={(trace.DidHit() ? at.ToString("F0") : "none")}");
            return trace.DidHit() && MathF.Abs(at - expected) <= GrassWallTolerance;
        }
        var ok = true;
        foreach (var sy in new[] { 900f, -900f })
        foreach (var sx in new[] { 1f, -1f })
            ok &= Wall(new Vector(0, sy, knee), new Vector(sx, 0, 0), FoundationWallPlaneX, true);
        foreach (var sx in new[] { 700f, -700f })
        foreach (var sy in new[] { 1f, -1f })
            ok &= Wall(new Vector(sx, 0, knee), new Vector(0, sy, 0), FoundationWallPlaneY, false);
        detail = $"floorZ={floor:F2} walls={string.Join(',', walls)}";
        return ok ? floor : null;
    }

    private void GrassCheckTransmit(CCheckTransmitInfoList infoList)
    {
        if (_grassTiles.Count == 0) return;
        foreach ((CCheckTransmitInfo info, CCSPlayerController? receiver) in infoList)
        {
            if (receiver is not { IsValid: true } || GrassOn(receiver)) continue;
            foreach (var tile in _grassTiles) if (tile.IsValid) info.TransmitEntities.Remove(tile);
        }
    }

    private void OnGrassCommand(CCSPlayerController? player, CommandInfo command)
    {
        if (player is not { IsValid: true }) return;
        var arg = command.ArgCount >= 2 ? command.GetArg(1).ToLowerInvariant() : "";
        var on = arg switch { "on" => true, "off" => false, _ => !GrassOn(player) };
        SetGrass(player, on);
        if (!GrassAvailable) player.PrintToChat(" \x04[SM]\x01 This map has no 3D grass (the pitch does not match the SoccerMod stadium).");
    }

    private void OnGrassAdminCommand(CCSPlayerController? player, CommandInfo command)
    {
        if (!RequirePermission(player, command, "admin")) return;
        var arg = command.ArgCount >= 2 ? command.GetArg(1).ToLowerInvariant() : "status";
        switch (arg)
        {
            case "auto":
            case "off":
                _menuParity.GrassServerMode = arg;
                SaveJsonAtomic(MenuParityFile, _menuParity);
                if (arg == "off") RemoveGrass("admin_off"); else GrassEnsure("admin_auto");
                break;
            case "default" when command.ArgCount >= 3 && command.GetArg(2).ToLowerInvariant() is "on" or "off":
                _menuParity.GrassDefault = command.GetArg(2).Equals("on", StringComparison.OrdinalIgnoreCase);
                SaveJsonAtomic(MenuParityFile, _menuParity);
                break;
            case "recheck":
                _grassChecked = false;
                _grassFloorZ = null;
                RemoveGrass("admin_recheck");
                GrassEnsure("admin_recheck");
                break;
        }
        command.ReplyToCommand($"[SM] 3D grass: server={_menuParity.GrassServerMode}, default={(_menuParity.GrassDefault ? "on" : "off")}, " +
            $"installed={GrassInstalled()}, map compatible={(_grassChecked ? (_grassFloorZ is not null ? "yes" : "no") : "not checked yet")}, " +
            $"spawned={_grassTiles.Count(t => t.IsValid)} tiles (usage: css_sm2grass auto|off|recheck|default on|off)");
    }
}
